# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173m7LNXZrpm2-UFs27H34jHaSfBR9YPS
"""

# Crear una instancia de OrderList con algunos elementos iniciales
my_list = OrderList([10, 20, 30, 40, 50])
print(f"Lista inicial: {my_list}")

# Obtener la longitud de la lista
print(f"Longitud de la lista: {len(my_list)}")

# Acceder a un elemento por índice
print(f"Elemento en el índice 2: {my_list[2]}")

# Intentar acceder a un índice que no existe (debe mostrar el error)
print(f"Intentando acceder a un índice inexistente (10): {my_list[10]}")

# Verificar si la lista está vacía
print(f"¿La lista está vacía? {my_list.isEmpty()}")

# Añadir un elemento
my_list.add(60)
print(f"Lista después de añadir 60: {my_list}")

# Verificar la existencia de un elemento
print(f"¿La lista contiene 30? {30 in my_list}")
print(f"¿La lista contiene 99? {99 in my_list}")

# Eliminar un elemento por valor
my_list.remove(20)
print(f"Lista después de eliminar 20: {my_list}")

# Intentar eliminar un elemento que no existe (debe mostrar el error)
my_list.remove(99)

# Sacar un elemento por índice
elemento_sacado = my_list.pop(0)
print(f"Elemento sacado del índice 0: {elemento_sacado}")
print(f"Lista después de hacer pop: {my_list}")

# Intentar sacar un elemento de un índice que no existe (debe mostrar el error)
my_list.pop(10)

# Iterar sobre la lista
print("Elementos en la lista (iterando):")
for item in my_list:
    print(item)

# Limpiar la lista
my_list.clear()
print(f"Lista después de limpiar: {my_list}")
print(f"¿La lista está vacía ahora? {my_list.isEmpty()}")