# -*- coding: utf-8 -*-
"""taller estructura de datos lineales arraylist

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sevj3B-pK5TQU6UY4c188o9lE22Cwon

class ArrayList:
    
    # size: initial capacity of the collection
    # initial_elements: allow the collection to start with some elements
    def __init__(self, size=100, initial_elements=[]):
        pass
"""

class ArrayList:
    def __init__(self, size=100, initial_elements=[]):
       self.array = [None] * size
       self.capacity = size
       self.count = 0
       for personaje in initial_elements:
           if self.count < self.capacity:
               self.array[self.count] = personaje
               self.count += 1
           else:
               print("Error: La lista está llena")
               break
if __name__ == "__main__":
   mi_equipo = ArrayList(size=5, initial_elements=["tabibito", "Paimon", "Zhongli"])
   print(f"Capacidad total del arreglo: {mi_equipo.capacity}")
   print(f"Arreglo interno en memoria: {mi_equipo.array}")

"""# return an str of the collection
    def __str__(self):
        pass
"""

class ArrayList:
    def __init__(self, size=100, initial_elements=[]):
       self.array = [None] * size
       self.capacity = size
       self.count = 0
       for personaje in initial_elements:
           if self.count < self.capacity:
               self.array[self.count] = personaje
               self.count += 1
           else:
               break
    def __str__(self):
        personajes_reales = self.array[:self.count]
        return str(personajes_reales)
if __name__ == "__main__":
   mi_equipo = ArrayList(size=5, initial_elements=["tabibito", "Paimon", "Zhongli"])
   print("mi equipo de genshi es:", mi_equipo)

"""  # return a boolean that implies if the collection is empty or not
    def isEmpty(self):
        pass
"""

class ArrayList:
    def __init__(self, size=100, initial_elements=[]):
       self.array = [None] * size
       self.capacity = size
       self.count = 0
       for personaje in initial_elements:
           if self.count < self.capacity:
               self.array[self.count] = personaje
               self.count += 1
           else:
               break
    def __str__(self):
        personajes_reales = self.array[:self.count]
        return str(personajes_reales)
    def __len__(self):
        return self.count
if __name__ == "__main__":
  mi_equipo = ArrayList(size=10, initial_elements=["Raiden Shogun", "Yae Miko", "Sara"])
  cantidad_personajes = len(mi_equipo)
  print(mi_equipo)
  print(f"Tienes {cantidad_personajes} personajes en tu equipo.")

"""# return a boolean that implies if the collection is empty or not
    def isEmpty(self):
        pass
"""

class ArrayList:
    def __init__(self, size=100, initial_elements=[]):
       self.array = [None] * size
       self.capacity = size
       self.count = 0
       for personaje in initial_elements:
           if self.count < self.capacity:
               self.array[self.count] = personaje
               self.count += 1
           else:
               break
    def __str__(self):
        personajes_reales = self.array[:self.count]
        return str(personajes_reales)
    def __len__(self):
        return self.count
    def isEmpty(self):
        return self.count == 0
if __name__ == "__main__":
   equipo_vacio = ArrayList(size=5, initial_elements=[])
   print("¿El equipo está vacío?", equipo_vacio.isEmpty())
   equipo_natlan = ArrayList(size=5, initial_elements=["Mualani", "Kinich", "Kachina", "Mavuika"])
   print(f"Mi equipo de Natlan: {equipo_natlan}")
   print("¿El equipo de Natlan está vacío?", equipo_natlan.isEmpty())