# -*- coding: utf-8 -*-
"""taller estructura  de datos lineales  lista linkelin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QwjGXN-qmDmr6YHyojarXkpE0T67WblN

# initial_elements: allow the collection to start with some elements
    def __init__(self, initial_elements=[]):
        pass
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self, initial_elements=None):
        self.head = None
        if initial_elements is not None:
           for element in initial_elements:
               self.agregar(element)

    def agregar(self, data):
         nuevo_nodo = Node(data)
         if self.head is None:
             self.head = nuevo_nodo
             return
         ultimo = self.head
         while ultimo.next:
              ultimo = ultimo.next
         ultimo.next = nuevo_nodo

    def mostrar(self):
        frutas = []
        actual = self.head
        while actual:
             frutas.append(actual.data)
             actual = actual.next
        print(", ".join(frutas))

mi_canasta = LinkedList(["Manzana", "Banana", "Naranja"])
print("Lista inicial:")
mi_canasta.mostrar()
mi_canasta.agregar("Fresa")
mi_canasta.agregar("Mango")
print("\nLista después de agregar elementos:")
mi_canasta.mostrar()

""" # return an str of the collection
    def __str__(self):
        pass
"""

class node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self, initial_elements=None):
        self.head = None
        if initial_elements is not None:
           for element in initial_elements:
               self.agregar(element)
    def agregar(self, data):
        nuevo_nodo = node(data)
        if self.head is None:
            self.head = nuevo_nodo
            return
        ultimo = self.head
        while ultimo.next:
             ultimo = ultimo.next
        ultimo.next = nuevo_nodo
    def __str__(self):
        elementos = []
        actual = self.head
        while actual:
             elementos.append(str(actual.data))
             actual = actual.next
        return ",".join(elementos)

if __name__ == "__main__":
    mis_frutas = LinkedList(["Manzana", "Banana", "Naranja"])
    mis_frutas.agregar("Fresa")
    mis_frutas.agregar("Mango")

    print(mis_frutas)

"""# return the length of the elements in the collection
    def __len__(self):
        pass
"""

class node:
  def __init__(self, data):
    self.data = data
    self.next = None

class LinkedList:
     def __init__(self, initial_elements=None):
         self.head = None
         if initial_elements is not None:
            for element in initial_elements:
                self.agregar(element)
     def agregar(self, data):
         nuevo_nodo = node(data)
         if self.head is None:
             self.head = nuevo_nodo
             return
         ultimo = self.head
         while ultimo.next:
              ultimo = ultimo.next
         ultimo.next = nuevo_nodo
     def __str__(self):
         elementos = []
         actual = self.head
         while actual:
              elementos.append(str(actual.data))
              actual = actual.next
         return ",".join(elementos)
     def __len__(self):
      contador = 0
      actual = self.head
      while actual:
           contador += 1
           actual = actual.next
      return contador
if __name__ == "__main__":
   mis_frutas = LinkedList(["Manzana", "Banana", "Naranja", "Fresa", "Mango"])
   print("Mi lista:", mis_frutas)
   cantidad = len(mis_frutas)
   print(f"Total de frutas: {cantidad}")

"""  # return the element of the collection in the index possition
    # Error: the index dont exist
    def __getitem__(self, index):
        pass
"""

class node:
  def __init__(self, data):
    self.data = data
    self.next = None

class LinkedList:
  def __init__(self,initial_elements=None):
    self.head = None
    if initial_elements is not None:
      for element in initial_elements:
        self.agregar(element)
  def agregar(self, data):
    nuevo_nodo = node(data)
    if self.head is None:
      self.head = nuevo_nodo
      return
    ultimo = self.head
    while ultimo.next:
      ultimo = ultimo.next
    ultimo.next = nuevo_nodo
  def __str__(self):
      elementos = []
      actual = self.head
      while actual:
           elementos.append(str(actual.data))
           actual = actual.next
      return ",".join(elementos)
  def __len__(self):
    contador = 0
    actual = self.head
    while actual:
         contador += 1
         actual = actual.next
    return contador
  def __getitem__(self, index):
    if index < 0:
        raise IndexError("Índice no válido")
    actual = self.head
    posicion_actual = 0 # Changed from 1 to 0 for 0-based indexing
    while actual is not None:
        if posicion_actual == index:
            return actual.data
        actual = actual.next
        posicion_actual += 1
    raise IndexError("Índice fuera de rango")
if __name__ == "__main__":
    mis_frutas = LinkedList(["Manzana", "Banana", "Naranja"])
    print("Mi lista:", mis_frutas)
    print("La fruta en la posición 1 es:", mis_frutas[1])
    print("La fruta en la posición 0 es:", mis_frutas[0])